# Font
font_family FiraCode Nerd Font
font_size 11.0

# Cursor
cursor_shape block
cursor_blink_interval 0.5

# Window transparency
background_opacity 0.75
dynamic_background_opacity yes

# Window padding
window_padding_width 10
placement_strategy top-left

# Scrollback
scrollback_lines 10000

# Enable ligatures
disable_ligatures never

# Performance
repaint_delay 10
input_delay 3
sync_to_monitor yes

include theme.conf
